# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: andreasfertig/cppinsights-builder-gitpod:latest
workspaceLocation: "."

tasks:
    - init: "mkdir /workspace/build && cd /workspace/build && cmake -G Ninja -DINSIGHTS_STATIC=Yes -DINSIGHTS_COVERAGE=No -DINSIGHTS_LLVM_CONFIG=/usr/bin/llvm-config /workspace/cppinsights && echo \"Run: ninja -j2\""
