#[=======================================================================[
Copyright (c) by Vector Informatik GmbH. All rights reserved.

This software is copyright protected and proprietary to Vector Informatik GmbH.
Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
All other rights remain with Vector Informatik GmbH.

Attention:
----------
The ${target} property settings in this file only take effect if this file is
set as an expected OUTPUT of dvacgf_file_gen().

File description:
-----------------
This is a generated CMake build-configuration file, modifications get lost.
#]=======================================================================]


# Add generated header file(s) to target property SOURCES
target_sources(${target} PRIVATE
  "${CMAKE_CURRENT_LIST_DIR}/include/CalibrationSts/impl_type_calibrationsts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/Classification/impl_type_classification.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistX/impl_type_distx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistXStd/impl_type_distxstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistY/impl_type_disty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistYStd/impl_type_distystd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistZ/impl_type_distz.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistZStd/impl_type_distzstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DynamicProperty/impl_type_dynamicproperty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureE2E/impl_type_ecufailuree2e.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureNVM/impl_type_ecufailurenvm.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailurePlausibility/impl_type_ecufailureplausibility.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureQF/impl_type_ecufailureqf.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureTemperature/impl_type_ecufailuretemperature.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureUB/impl_type_ecufailureub.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVCS/impl_type_ecufailurevcs.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVDY/impl_type_ecufailurevdy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVoltage/impl_type_ecufailurevoltage.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrStsValid/impl_type_errstsvalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatus/impl_type_errorstatus.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse01_10/impl_type_errorstatuse01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse11_20/impl_type_errorstatuse11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse21_30/impl_type_errorstatuse21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse31_40/impl_type_errorstatuse31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse41_42/impl_type_errorstatuse41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDChks/impl_type_fourdchks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDChks/impl_type_fourdobjchks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDCntr/impl_type_fourdcntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDCntr/impl_type_fourdobjcntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDID/impl_type_fourdid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarECUSts/impl_type_fourdradarecusts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarECUStsGrpSts/impl_type_fourdradarecustsgrpsts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSt/impl_type_fourdradarobjst.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts01_10/impl_type_fourdradarobjsts01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts11_20/impl_type_fourdradarobjsts11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts21_30/impl_type_fourdradarobjsts21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts31_40/impl_type_fourdradarobjsts31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts41_42/impl_type_fourdradarobjsts41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp01_10/impl_type_fourdradarobjstsgrp01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp04/impl_type_fourdradarobjstsgrp31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp11_20/impl_type_fourdradarobjstsgrp11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp21_30/impl_type_fourdradarobjstsgrp21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp41_42/impl_type_fourdradarobjstsgrp41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FrontFourDRadarSts1Vcc/impl_type_frontfourdradarsts1vcc.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/HeadingAngle/impl_type_fourdheadingangle.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/LifeCycles/impl_type_lifecycles.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxHeight/impl_type_objboundingboxheight.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxLength/impl_type_objboundingboxlength.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxWidth/impl_type_objboundingboxwidth.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtX/impl_type_objnearestptx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtY/impl_type_objnearestpty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtZ/impl_type_objnearestptz.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjSNR/impl_type_objsnr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjValid/impl_type_objvalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjXAccRel/impl_type_objxaccrel.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjYAccRel/impl_type_objyaccrel.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObstacleProbability/impl_type_obstacleprobability.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/OperationMode/impl_type_operationmode.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ProbabilityOfExistence/impl_type_probabilityofexistence.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RCS/impl_type_rcs.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrNrDetn/impl_type_rdrstsrdrnrdetn.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsBlkd0bin/impl_type_rdrstsblkd0bin.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsBlkdConf/impl_type_rdrstsblkdconf.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsChks/impl_type_rdrstschks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsCntr/impl_type_rdrstscntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsDstbc/impl_type_rdrstsdstbc.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsEna/impl_type_rdrstsena.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsFaulty/impl_type_rdrstsfaulty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsIfVersMajor/impl_type_rdrstsifversmajor.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsIfVersMinor/impl_type_rdrstsifversminor.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsLatency/impl_type_rdrstslatency.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsMisAlign/impl_type_rdrstsmisalign.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsMissCom/impl_type_rdrstsmisscom.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsRdrNrObj/impl_type_rdrstsrdrnrobj.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsSftyFlt/impl_type_rdrstssftyflt.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampH/impl_type_rdrststistamph.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampL/impl_type_rdrststistampl.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsGlbTiBas/impl_type_rdrststistampstsglbtibas.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsSyncToGatewy/impl_type_rdrststistampstssynctogatewy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsTiLeap/impl_type_rdrststistampststileap.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsTiOut/impl_type_rdrststistampststiout.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsWhlSpdCmpFac/impl_type_rdrstswhlspdcmpfac.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid/impl_type_tfourdradardatavalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid01_10/impl_type_tfourdradardatavalid01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid11_20/impl_type_tfourdradardatavalid11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid21_30/impl_type_tfourdradardatavalid21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid31_40/impl_type_tfourdradardatavalid31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid41_42/impl_type_tfourdradardatavalid41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TargetClassificationConfidence/impl_type_targetclassificationconfidence.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/UpdateFlag/impl_type_updateflag.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsX/impl_type_vabsx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsXStd/impl_type_vabsxstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsY/impl_type_vabsy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsYStd/impl_type_vabsystd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ValidFlag/impl_type_validflag.h"
)

# Mark header file(s) as generated
set_source_files_properties(
  "${CMAKE_CURRENT_LIST_DIR}/include/CalibrationSts/impl_type_calibrationsts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/Classification/impl_type_classification.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistX/impl_type_distx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistXStd/impl_type_distxstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistY/impl_type_disty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistYStd/impl_type_distystd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistZ/impl_type_distz.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DistZStd/impl_type_distzstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/DynamicProperty/impl_type_dynamicproperty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureE2E/impl_type_ecufailuree2e.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureNVM/impl_type_ecufailurenvm.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailurePlausibility/impl_type_ecufailureplausibility.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureQF/impl_type_ecufailureqf.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureTemperature/impl_type_ecufailuretemperature.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureUB/impl_type_ecufailureub.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVCS/impl_type_ecufailurevcs.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVDY/impl_type_ecufailurevdy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ECUFailureVoltage/impl_type_ecufailurevoltage.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrStsValid/impl_type_errstsvalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatus/impl_type_errorstatus.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse01_10/impl_type_errorstatuse01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse11_20/impl_type_errorstatuse11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse21_30/impl_type_errorstatuse21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse31_40/impl_type_errorstatuse31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ErrorStatuse41_42/impl_type_errorstatuse41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDChks/impl_type_fourdchks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDChks/impl_type_fourdobjchks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDCntr/impl_type_fourdcntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDCntr/impl_type_fourdobjcntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDID/impl_type_fourdid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarECUSts/impl_type_fourdradarecusts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarECUStsGrpSts/impl_type_fourdradarecustsgrpsts.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSt/impl_type_fourdradarobjst.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts01_10/impl_type_fourdradarobjsts01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts11_20/impl_type_fourdradarobjsts11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts21_30/impl_type_fourdradarobjsts21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts31_40/impl_type_fourdradarobjsts31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjSts41_42/impl_type_fourdradarobjsts41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp01_10/impl_type_fourdradarobjstsgrp01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp04/impl_type_fourdradarobjstsgrp31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp11_20/impl_type_fourdradarobjstsgrp11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp21_30/impl_type_fourdradarobjstsgrp21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FourDRadarObjStsGrp41_42/impl_type_fourdradarobjstsgrp41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/FrontFourDRadarSts1Vcc/impl_type_frontfourdradarsts1vcc.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/HeadingAngle/impl_type_fourdheadingangle.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/LifeCycles/impl_type_lifecycles.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxHeight/impl_type_objboundingboxheight.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxLength/impl_type_objboundingboxlength.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjBoundingBoxWidth/impl_type_objboundingboxwidth.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtX/impl_type_objnearestptx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtY/impl_type_objnearestpty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjNearestPtZ/impl_type_objnearestptz.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjSNR/impl_type_objsnr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjValid/impl_type_objvalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjXAccRel/impl_type_objxaccrel.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObjYAccRel/impl_type_objyaccrel.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ObstacleProbability/impl_type_obstacleprobability.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/OperationMode/impl_type_operationmode.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ProbabilityOfExistence/impl_type_probabilityofexistence.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RCS/impl_type_rcs.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrNrDetn/impl_type_rdrstsrdrnrdetn.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsBlkd0bin/impl_type_rdrstsblkd0bin.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsBlkdConf/impl_type_rdrstsblkdconf.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsChks/impl_type_rdrstschks.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsCntr/impl_type_rdrstscntr.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsDstbc/impl_type_rdrstsdstbc.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsEna/impl_type_rdrstsena.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsFaulty/impl_type_rdrstsfaulty.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsIfVersMajor/impl_type_rdrstsifversmajor.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsIfVersMinor/impl_type_rdrstsifversminor.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsLatency/impl_type_rdrstslatency.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsMisAlign/impl_type_rdrstsmisalign.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsMissCom/impl_type_rdrstsmisscom.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsRdrNrObj/impl_type_rdrstsrdrnrobj.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsSftyFlt/impl_type_rdrstssftyflt.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampH/impl_type_rdrststistamph.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampL/impl_type_rdrststistampl.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsGlbTiBas/impl_type_rdrststistampstsglbtibas.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsSyncToGatewy/impl_type_rdrststistampstssynctogatewy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsTiLeap/impl_type_rdrststistampststileap.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsTiStampStsTiOut/impl_type_rdrststistampststiout.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/RdrStsWhlSpdCmpFac/impl_type_rdrstswhlspdcmpfac.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid/impl_type_tfourdradardatavalid.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid01_10/impl_type_tfourdradardatavalid01_10.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid11_20/impl_type_tfourdradardatavalid11_20.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid21_30/impl_type_tfourdradardatavalid21_30.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid31_40/impl_type_tfourdradardatavalid31_40.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TFourDRadarDataValid41_42/impl_type_tfourdradardatavalid41_42.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/TargetClassificationConfidence/impl_type_targetclassificationconfidence.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/UpdateFlag/impl_type_updateflag.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsX/impl_type_vabsx.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsXStd/impl_type_vabsxstd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsY/impl_type_vabsy.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/VabsYStd/impl_type_vabsystd.h"
  "${CMAKE_CURRENT_LIST_DIR}/include/ValidFlag/impl_type_validflag.h"
  PROPERTIES GENERATED 1
)

# Add include directory of generated header file(s)
target_include_directories(${target} PRIVATE # No public interface for executables
  "${CMAKE_CURRENT_LIST_DIR}/include"
)

