(cl:in-package data_parse-msg)
(cl:export '(HEADER-VAL
          HEADER
          LANES_ADJACENT_COUNT-VAL
          LANES_ADJACENT_COUNT
          ADJACENT_TYPE-VAL
          ADJACENT_TYPE
          ADJACENT_CONFIDENCE-VAL
          ADJACENT_CONFIDENCE
          ADJACENT_VIEW_RANGE_START-VAL
          ADJACENT_VIEW_RANGE_START
          ADJACENT_VIEW_RANGE_END-VAL
          ADJACENT_VIEW_RANGE_END
          ADJACENT_LINE_ROLE-VAL
          ADJACENT_LINE_ROLE
          ADJACENT_LINE_C-VAL
          ADJACENT_LINE_C
))