// Generated by gencpp from file data_parse/SensorFovList.msg
// DO NOT EDIT!


#ifndef DATA_PARSE_MESSAGE_SENSORFOVLIST_H
#define DATA_PARSE_MESSAGE_SENSORFOVLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <data_parse/SensorFovData.h>

namespace data_parse
{
template <class ContainerAllocator>
struct SensorFovList_
{
  typedef SensorFovList_<ContainerAllocator> Type;

  SensorFovList_()
    : header()
    , sensor_fov_list()  {
    }
  SensorFovList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_fov_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::data_parse::SensorFovData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::data_parse::SensorFovData_<ContainerAllocator> >> _sensor_fov_list_type;
  _sensor_fov_list_type sensor_fov_list;





  typedef boost::shared_ptr< ::data_parse::SensorFovList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_parse::SensorFovList_<ContainerAllocator> const> ConstPtr;

}; // struct SensorFovList_

typedef ::data_parse::SensorFovList_<std::allocator<void> > SensorFovList;

typedef boost::shared_ptr< ::data_parse::SensorFovList > SensorFovListPtr;
typedef boost::shared_ptr< ::data_parse::SensorFovList const> SensorFovListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_parse::SensorFovList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_parse::SensorFovList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_parse::SensorFovList_<ContainerAllocator1> & lhs, const ::data_parse::SensorFovList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor_fov_list == rhs.sensor_fov_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_parse::SensorFovList_<ContainerAllocator1> & lhs, const ::data_parse::SensorFovList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_parse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::data_parse::SensorFovList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_parse::SensorFovList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_parse::SensorFovList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_parse::SensorFovList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_parse::SensorFovList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_parse::SensorFovList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_parse::SensorFovList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b098137c9a7ca98e3e4f0e068c13d0bd";
  }

  static const char* value(const ::data_parse::SensorFovList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb098137c9a7ca98eULL;
  static const uint64_t static_value2 = 0x3e4f0e068c13d0bdULL;
};

template<class ContainerAllocator>
struct DataType< ::data_parse::SensorFovList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_parse/SensorFovList";
  }

  static const char* value(const ::data_parse::SensorFovList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_parse::SensorFovList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "################################################################################\n"
"#\n"
"# Sensor Fov List\n"
"#\n"
"# Description:\n"
"#   Interface for a list of sensor fov data\n"
"#\n"
"################################################################################\n"
"\n"
"# ROS Header\n"
"Header header\n"
"\n"
"# List of sensor fov data\n"
"SensorFovData[] sensor_fov_list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: data_parse/SensorFovData\n"
"################################################################################\n"
"#\n"
"# Sensor Fov Data\n"
"#\n"
"# Description:\n"
"#   Interface for describing the fov of a sensor, normally we use circle sector\n"
"#   to decribe the field of view of sensor data\n"
"#\n"
"#\n"
"#\n"
"################################################################################\n"
"\n"
"# device id\n"
"uint8 device_id\n"
"\n"
"# [m] the position based on the ego_rear_axis\n"
"geometry_msgs/Vector3 position\n"
"\n"
"# [rad] the opening angle of the sensor view\n"
"float32 opening_angle\n"
"\n"
"# [rad] the yaw angle of the sensor based on the x axis of ego_rear_axis\n"
"float32 yaw_angle\n"
"\n"
"# [m] minimum range of sensor detection in meter\n"
"# normally the close blind spot distance of this sensor\n"
"float32 min_range\n"
"\n"
"# [m] max range of sensor detection in meter\n"
"float32 max_range\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::data_parse::SensorFovList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_parse::SensorFovList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_fov_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorFovList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_parse::SensorFovList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_parse::SensorFovList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_fov_list[]" << std::endl;
    for (size_t i = 0; i < v.sensor_fov_list.size(); ++i)
    {
      s << indent << "  sensor_fov_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::data_parse::SensorFovData_<ContainerAllocator> >::stream(s, indent + "    ", v.sensor_fov_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_PARSE_MESSAGE_SENSORFOVLIST_H
