std_msgs/Header header

float64 HostSpeed
float64 HostYawRate
float64 StsBlkd0bin
uint8 StsBlkdConf
uint8 StsChks
uint8 StsCntr
uint8 StsDstbc
uint8 StsEna
uint8 StsFaulty
uint8 StsIfVersMajor
uint8 StsIfVersMinor
float64 StsLatency
uint8 StsMisAlign
uint8 StsMissCom
uint8 StsRdrNrDetn
uint8 StsRdrNrObj
uint8 StsSftyFlt
float64 StsTiStamp
uint8 StsWhlSpdCmpFac
uint8 TiStampStsGlbTiBas
uint8 TiStampStsSyncToGatewy
uint8 TiStampStsTiLeap
uint8 TiStampStsTiOut

uint8 sensor_type

uint8 Blockage
uint8 Calibration
uint8 Fault

Object[] objects