# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from data_parse/EgoLane.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import data_parse.msg
import std_msgs.msg

class EgoLane(genpy.Message):
  _md5sum = "c853a0afe8c4bc08d024aa3177156a39"
  _type = "data_parse/EgoLane"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

bool Is_Construction_Area

float64 LH_Confidence

# enum
uint8 LH_Lanemark_Type 
uint8 UNDECIDED = 0
uint8 SOLID = 1
uint8 DASHED = 2
uint8 DLM = 3 
uint8 BOTTS = 4
uint8 DECELERATION = 5
uint8 HOV_LANE = 6

# enum
uint8 LH_Side
uint8 UNKNOWN = 0
uint8 LEFT = 1
uint8 RIGHT = 2

float64 LH_VR_Start
float64 LH_VR_End

LHParam LH_C




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: data_parse/LHParam
float64 LH_C0
float64 LH_C1
float64 LH_C2
float64 LH_C3"""
  # Pseudo-constants
  UNDECIDED = 0
  SOLID = 1
  DASHED = 2
  DLM = 3
  BOTTS = 4
  DECELERATION = 5
  HOV_LANE = 6
  UNKNOWN = 0
  LEFT = 1
  RIGHT = 2

  __slots__ = ['header','Is_Construction_Area','LH_Confidence','LH_Lanemark_Type','LH_Side','LH_VR_Start','LH_VR_End','LH_C']
  _slot_types = ['std_msgs/Header','bool','float64','uint8','uint8','float64','float64','data_parse/LHParam']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Is_Construction_Area,LH_Confidence,LH_Lanemark_Type,LH_Side,LH_VR_Start,LH_VR_End,LH_C

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EgoLane, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Is_Construction_Area is None:
        self.Is_Construction_Area = False
      if self.LH_Confidence is None:
        self.LH_Confidence = 0.
      if self.LH_Lanemark_Type is None:
        self.LH_Lanemark_Type = 0
      if self.LH_Side is None:
        self.LH_Side = 0
      if self.LH_VR_Start is None:
        self.LH_VR_Start = 0.
      if self.LH_VR_End is None:
        self.LH_VR_End = 0.
      if self.LH_C is None:
        self.LH_C = data_parse.msg.LHParam()
    else:
      self.header = std_msgs.msg.Header()
      self.Is_Construction_Area = False
      self.LH_Confidence = 0.
      self.LH_Lanemark_Type = 0
      self.LH_Side = 0
      self.LH_VR_Start = 0.
      self.LH_VR_End = 0.
      self.LH_C = data_parse.msg.LHParam()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bd2B6d().pack(_x.Is_Construction_Area, _x.LH_Confidence, _x.LH_Lanemark_Type, _x.LH_Side, _x.LH_VR_Start, _x.LH_VR_End, _x.LH_C.LH_C0, _x.LH_C.LH_C1, _x.LH_C.LH_C2, _x.LH_C.LH_C3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.LH_C is None:
        self.LH_C = data_parse.msg.LHParam()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.Is_Construction_Area, _x.LH_Confidence, _x.LH_Lanemark_Type, _x.LH_Side, _x.LH_VR_Start, _x.LH_VR_End, _x.LH_C.LH_C0, _x.LH_C.LH_C1, _x.LH_C.LH_C2, _x.LH_C.LH_C3,) = _get_struct_Bd2B6d().unpack(str[start:end])
      self.Is_Construction_Area = bool(self.Is_Construction_Area)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bd2B6d().pack(_x.Is_Construction_Area, _x.LH_Confidence, _x.LH_Lanemark_Type, _x.LH_Side, _x.LH_VR_Start, _x.LH_VR_End, _x.LH_C.LH_C0, _x.LH_C.LH_C1, _x.LH_C.LH_C2, _x.LH_C.LH_C3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.LH_C is None:
        self.LH_C = data_parse.msg.LHParam()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.Is_Construction_Area, _x.LH_Confidence, _x.LH_Lanemark_Type, _x.LH_Side, _x.LH_VR_Start, _x.LH_VR_End, _x.LH_C.LH_C0, _x.LH_C.LH_C1, _x.LH_C.LH_C2, _x.LH_C.LH_C3,) = _get_struct_Bd2B6d().unpack(str[start:end])
      self.Is_Construction_Area = bool(self.Is_Construction_Area)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bd2B6d = None
def _get_struct_Bd2B6d():
    global _struct_Bd2B6d
    if _struct_Bd2B6d is None:
        _struct_Bd2B6d = struct.Struct("<Bd2B6d")
    return _struct_Bd2B6d
