# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from data_parse/JiCaEgoMotion.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class JiCaEgoMotion(genpy.Message):
  _md5sum = "54d9e18c5aea7a54f5520145e95dc662"
  _type = "data_parse/JiCaEgoMotion"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

float64 speed
float64 lat_velocity
float64 lgt_velocity
float64 lat_accel
float64 lgt_accel
float64 yaw_rate
float64 PosnLgtDelta
float64 PosnLatDelta
float64 AgDirDelta
float64 avert
float64 roll_rate
float64 time_stamp
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','speed','lat_velocity','lgt_velocity','lat_accel','lgt_accel','yaw_rate','PosnLgtDelta','PosnLatDelta','AgDirDelta','avert','roll_rate','time_stamp']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,speed,lat_velocity,lgt_velocity,lat_accel,lgt_accel,yaw_rate,PosnLgtDelta,PosnLatDelta,AgDirDelta,avert,roll_rate,time_stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JiCaEgoMotion, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.speed is None:
        self.speed = 0.
      if self.lat_velocity is None:
        self.lat_velocity = 0.
      if self.lgt_velocity is None:
        self.lgt_velocity = 0.
      if self.lat_accel is None:
        self.lat_accel = 0.
      if self.lgt_accel is None:
        self.lgt_accel = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.PosnLgtDelta is None:
        self.PosnLgtDelta = 0.
      if self.PosnLatDelta is None:
        self.PosnLatDelta = 0.
      if self.AgDirDelta is None:
        self.AgDirDelta = 0.
      if self.avert is None:
        self.avert = 0.
      if self.roll_rate is None:
        self.roll_rate = 0.
      if self.time_stamp is None:
        self.time_stamp = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.speed = 0.
      self.lat_velocity = 0.
      self.lgt_velocity = 0.
      self.lat_accel = 0.
      self.lgt_accel = 0.
      self.yaw_rate = 0.
      self.PosnLgtDelta = 0.
      self.PosnLatDelta = 0.
      self.AgDirDelta = 0.
      self.avert = 0.
      self.roll_rate = 0.
      self.time_stamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.speed, _x.lat_velocity, _x.lgt_velocity, _x.lat_accel, _x.lgt_accel, _x.yaw_rate, _x.PosnLgtDelta, _x.PosnLatDelta, _x.AgDirDelta, _x.avert, _x.roll_rate, _x.time_stamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.speed, _x.lat_velocity, _x.lgt_velocity, _x.lat_accel, _x.lgt_accel, _x.yaw_rate, _x.PosnLgtDelta, _x.PosnLatDelta, _x.AgDirDelta, _x.avert, _x.roll_rate, _x.time_stamp,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.speed, _x.lat_velocity, _x.lgt_velocity, _x.lat_accel, _x.lgt_accel, _x.yaw_rate, _x.PosnLgtDelta, _x.PosnLatDelta, _x.AgDirDelta, _x.avert, _x.roll_rate, _x.time_stamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.speed, _x.lat_velocity, _x.lgt_velocity, _x.lat_accel, _x.lgt_accel, _x.yaw_rate, _x.PosnLgtDelta, _x.PosnLatDelta, _x.AgDirDelta, _x.avert, _x.roll_rate, _x.time_stamp,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
