
#ifndef CAMCONVERTER_CFG_H_
#define CAMCONVERTER_CFG_H_ 1

#ifdef __cplusplus
extern "C" {
#endif

 
/*==================[macros]================================================*/

/** Class Type Vehicle / Truck */
/** Position X */
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_0   (1.22500f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_1   (0.24120f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_3   (-0.0009f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_4   (0.06440f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_X_MAX      (10.0f)

/** Position Y */
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_0   (0.10750f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_1   (-0.0079f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_3   (0.00020f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_4   (0.01400f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_POS_Y_MAX      (1.73210f)

/** Velocity X */
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_0   (3.51740f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_1   (-0.1411f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_3   (0.00170f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_4   (0.01870f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_MIN      (FLT_ONE)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_X_MAX      (4.4721f)

/** Velocity Y */
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_0   (0.08500f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_1   (0.00970f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_3   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_4   (0.00120f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_VEHICLE_VEL_Y_MAX      (2.23610f)

/** Class Type Pedestrian / Bicycle */
/** Position X */
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_0   (0.01270f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_1   (0.39850f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_3   (-0.0038f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_4   (0.05960f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_X_MAX      (3.16230f)

/** Position Y */
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_0   (0.17140f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_1   (0.03000f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_3   (-0.0006f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_4   (0.00860f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_POS_Y_MAX      (1.73210f)

/** Velocity X */
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_0   (0.83380f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_1   (-0.0135f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_3   (-0.0002f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_4   (0.01120f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_X_MAX      (4.47210f)

/** Velocity Y */
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_0   (0.07890f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_1   (-0.0028f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_2   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_3   (0.00010f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_4   (0.00030f)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_5   (FLT_ZERO)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_MIN      (JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_BETA_0)
#define  JKOBJLIST_MVS_SENSOR_MODEL_PEDESTRIAN_VEL_Y_MAX      (3.23610f)

#define  JKOBJLIST_MVS_LATENCY_TO_SECONDS                     (1000.0f)

/*==================[function]====================================*/

/*==================[external constants]====================================*/

#ifdef __cplusplus
}
#endif

#endif /* CAMCONVERTER_CFG_H_ */
