// Generated by gencpp from file data_parse/AdjacentLane.msg
// DO NOT EDIT!


#ifndef DATA_PARSE_MESSAGE_ADJACENTLANE_H
#define DATA_PARSE_MESSAGE_ADJACENTLANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <data_parse/LHParam.h>

namespace data_parse
{
template <class ContainerAllocator>
struct AdjacentLane_
{
  typedef AdjacentLane_<ContainerAllocator> Type;

  AdjacentLane_()
    : header()
    , Lanes_Adjacent_Count(0)
    , Adjacent_Type(0)
    , Adjacent_Confidence(0.0)
    , Adjacent_View_Range_Start(0.0)
    , Adjacent_View_Range_End(0.0)
    , Adjacent_Line_Role(0)
    , Adjacent_Line_C()  {
    }
  AdjacentLane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Lanes_Adjacent_Count(0)
    , Adjacent_Type(0)
    , Adjacent_Confidence(0.0)
    , Adjacent_View_Range_Start(0.0)
    , Adjacent_View_Range_End(0.0)
    , Adjacent_Line_Role(0)
    , Adjacent_Line_C(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Lanes_Adjacent_Count_type;
  _Lanes_Adjacent_Count_type Lanes_Adjacent_Count;

   typedef uint8_t _Adjacent_Type_type;
  _Adjacent_Type_type Adjacent_Type;

   typedef double _Adjacent_Confidence_type;
  _Adjacent_Confidence_type Adjacent_Confidence;

   typedef double _Adjacent_View_Range_Start_type;
  _Adjacent_View_Range_Start_type Adjacent_View_Range_Start;

   typedef double _Adjacent_View_Range_End_type;
  _Adjacent_View_Range_End_type Adjacent_View_Range_End;

   typedef uint8_t _Adjacent_Line_Role_type;
  _Adjacent_Line_Role_type Adjacent_Line_Role;

   typedef  ::data_parse::LHParam_<ContainerAllocator>  _Adjacent_Line_C_type;
  _Adjacent_Line_C_type Adjacent_Line_C;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNDECIDED)
  #undef UNDECIDED
#endif
#if defined(_WIN32) && defined(SOLID)
  #undef SOLID
#endif
#if defined(_WIN32) && defined(DASHED)
  #undef DASHED
#endif
#if defined(_WIN32) && defined(DLM)
  #undef DLM
#endif
#if defined(_WIN32) && defined(BOTTS)
  #undef BOTTS
#endif
#if defined(_WIN32) && defined(DECELERATION)
  #undef DECELERATION
#endif
#if defined(_WIN32) && defined(HOV_LANE)
  #undef HOV_LANE
#endif
#if defined(_WIN32) && defined(NONE)
  #undef NONE
#endif
#if defined(_WIN32) && defined(LEFT__LEFT_LANEMARK)
  #undef LEFT__LEFT_LANEMARK
#endif
#if defined(_WIN32) && defined(LEFT__RIGHT_LANEMARK)
  #undef LEFT__RIGHT_LANEMARK
#endif
#if defined(_WIN32) && defined(RIGHT__LEFT_LANEMARK)
  #undef RIGHT__LEFT_LANEMARK
#endif
#if defined(_WIN32) && defined(RIGHT__RIGHT_LANEMARK)
  #undef RIGHT__RIGHT_LANEMARK
#endif

  enum {
    UNDECIDED = 0u,
    SOLID = 1u,
    DASHED = 2u,
    DLM = 3u,
    BOTTS = 4u,
    DECELERATION = 5u,
    HOV_LANE = 6u,
    NONE = 0u,
    LEFT__LEFT_LANEMARK = 1u,
    LEFT__RIGHT_LANEMARK = 2u,
    RIGHT__LEFT_LANEMARK = 3u,
    RIGHT__RIGHT_LANEMARK = 4u,
  };


  typedef boost::shared_ptr< ::data_parse::AdjacentLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_parse::AdjacentLane_<ContainerAllocator> const> ConstPtr;

}; // struct AdjacentLane_

typedef ::data_parse::AdjacentLane_<std::allocator<void> > AdjacentLane;

typedef boost::shared_ptr< ::data_parse::AdjacentLane > AdjacentLanePtr;
typedef boost::shared_ptr< ::data_parse::AdjacentLane const> AdjacentLaneConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_parse::AdjacentLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_parse::AdjacentLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_parse::AdjacentLane_<ContainerAllocator1> & lhs, const ::data_parse::AdjacentLane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Lanes_Adjacent_Count == rhs.Lanes_Adjacent_Count &&
    lhs.Adjacent_Type == rhs.Adjacent_Type &&
    lhs.Adjacent_Confidence == rhs.Adjacent_Confidence &&
    lhs.Adjacent_View_Range_Start == rhs.Adjacent_View_Range_Start &&
    lhs.Adjacent_View_Range_End == rhs.Adjacent_View_Range_End &&
    lhs.Adjacent_Line_Role == rhs.Adjacent_Line_Role &&
    lhs.Adjacent_Line_C == rhs.Adjacent_Line_C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_parse::AdjacentLane_<ContainerAllocator1> & lhs, const ::data_parse::AdjacentLane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_parse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::data_parse::AdjacentLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_parse::AdjacentLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_parse::AdjacentLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_parse::AdjacentLane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_parse::AdjacentLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_parse::AdjacentLane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_parse::AdjacentLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58e1312381e41b759ad9062603e465e3";
  }

  static const char* value(const ::data_parse::AdjacentLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58e1312381e41b75ULL;
  static const uint64_t static_value2 = 0x9ad9062603e465e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_parse::AdjacentLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_parse/AdjacentLane";
  }

  static const char* value(const ::data_parse::AdjacentLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_parse::AdjacentLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 Lanes_Adjacent_Count\n"
"# enum\n"
"uint8 Adjacent_Type\n"
"uint8 UNDECIDED = 0\n"
"uint8 SOLID = 1\n"
"uint8 DASHED = 2\n"
"uint8 DLM = 3 \n"
"uint8 BOTTS = 4\n"
"uint8 DECELERATION = 5\n"
"uint8 HOV_LANE = 6\n"
"\n"
"float64 Adjacent_Confidence\n"
"float64 Adjacent_View_Range_Start\n"
"float64 Adjacent_View_Range_End\n"
"\n"
"# enum\n"
"uint8 Adjacent_Line_Role\n"
"uint8 NONE = 0\n"
"uint8 LEFT__LEFT_LANEMARK = 1\n"
"uint8 LEFT__RIGHT_LANEMARK = 2\n"
"uint8 RIGHT__LEFT_LANEMARK = 3\n"
"uint8 RIGHT__RIGHT_LANEMARK = 4\n"
"\n"
"LHParam Adjacent_Line_C\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: data_parse/LHParam\n"
"float64 LH_C0\n"
"float64 LH_C1\n"
"float64 LH_C2\n"
"float64 LH_C3\n"
;
  }

  static const char* value(const ::data_parse::AdjacentLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_parse::AdjacentLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Lanes_Adjacent_Count);
      stream.next(m.Adjacent_Type);
      stream.next(m.Adjacent_Confidence);
      stream.next(m.Adjacent_View_Range_Start);
      stream.next(m.Adjacent_View_Range_End);
      stream.next(m.Adjacent_Line_Role);
      stream.next(m.Adjacent_Line_C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdjacentLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_parse::AdjacentLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_parse::AdjacentLane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Lanes_Adjacent_Count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Lanes_Adjacent_Count);
    s << indent << "Adjacent_Type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Adjacent_Type);
    s << indent << "Adjacent_Confidence: ";
    Printer<double>::stream(s, indent + "  ", v.Adjacent_Confidence);
    s << indent << "Adjacent_View_Range_Start: ";
    Printer<double>::stream(s, indent + "  ", v.Adjacent_View_Range_Start);
    s << indent << "Adjacent_View_Range_End: ";
    Printer<double>::stream(s, indent + "  ", v.Adjacent_View_Range_End);
    s << indent << "Adjacent_Line_Role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Adjacent_Line_Role);
    s << indent << "Adjacent_Line_C: ";
    s << std::endl;
    Printer< ::data_parse::LHParam_<ContainerAllocator> >::stream(s, indent + "  ", v.Adjacent_Line_C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_PARSE_MESSAGE_ADJACENTLANE_H
